oUF_Smee_Settings = {
	profile = {
		enabledDebugMessages = false,
		enabled = true,		
		hideBlizzard = {
			TemporaryEnchantFrame = true,
			BuffFrame = true,
		},
		colors = {
			class = {
				["DEATHKNIGHT"] = { 0.77, 0.12, 0.23 },
				["DRUID"] = { 1.0 , 0.49, 0.04 },
				["HUNTER"] = { 0.67, 0.83, 0.45 },
				["MAGE"] = { 0.41, 0.8 , 0.94 },
				["PALADIN"] = { 0.96, 0.55, 0.73 },
				["PRIEST"] = { 1.0 , 1.0 , 1.0 },
				["ROGUE"] = { 1.0 , 0.96, 0.41 },
				["SHAMAN"] = { 0,0.86,0.73 },
				["WARLOCK"] = { 0.58, 0.51, 0.7 },
				["WARRIOR"] = { 0.78, 0.61, 0.43 },
			},
			backdropColors = {0,0,0},
			castbars = {
				bgColor = {1,1,1,.3},
				StatusBarColor = {0,0,0,0.6},
				BackdropColor = {0,0,0,1},
				Backdrop = {
					bgFile = "Interface\\Tooltips\\UI-Tooltip-Background", tile = true, tileSize = 16,
					insets = {left = -1.5, right = -1.5, top = -1.5, bottom = -1.5},
				},
				safezoneColor = {1, .2, .2, .5}
			},
			runes={
				[1] = {0.77, 0.12, 0.23},
				[2] = {0.3, 0.8, 0.1},
				[3] = {0, 0.4, 0.7},
				[4] = {0.2, 0.2, 0.2},
			},
		},
		classification = {
			worldboss = '%s |cffD7BEA5Boss|r',
			rareelite = '%s |cff%02x%02x%02x%s|r|cffD7BEA5+ R|r',
			elite = '%s |cff%02x%02x%02x%s|r|cffD7BEA5+|r',
			rare = '%s |cff%02x%02x%02x%s|r |cffD7BEA5R|r',
			normal = '%s |cff%02x%02x%02x%s|r',
			trivial = '%s |cff%02x%02x%02x%s|r',
		},
		textures = {
			backgrounds = {
				default = {
					bgFile = "Interface\\BUTTONS\\WHITE8x8", tile = true, tileSize = 16,
					insets = {left = -1.5, right = -1.5, top = -1.5, bottom = -1.5},
				},
			},
			statusbars = {
				default	= "Interface\\Addons\\oUF_Smee2\\media\\statusbars\\default",
				gloss		= "Interface\\Addons\\oUF_Smee2\\media\\statusbars\\gloss",
				slimDa		= "Interface\\Addons\\oUF_Smee2\\media\\statusbars\\slim-dA",
				slimDm		= "Interface\\Addons\\oUF_Smee2\\media\\statusbars\\slim-dM",
				slimDo		= "Interface\\Addons\\oUF_Smee2\\media\\statusbars\\slim-dO",
				slimDp		= "Interface\\Addons\\oUF_Smee2\\media\\statusbars\\slim-dP",
				slimDq		= "Interface\\Addons\\oUF_Smee2\\media\\statusbars\\slim-dQ",
				slimDr		= "Interface\\Addons\\oUF_Smee2\\media\\statusbars\\slim-dR",
				slimDu		= "Interface\\Addons\\oUF_Smee2\\media\\statusbars\\slim-dU",
			},
			borders = {
				default = "Interface\\Addons\\oUF_Smee2\\media\\borders\\default",
				slimbuff = "Interface\\Addons\\oUF_Smee2\\media\\borders\\slim-buff",
				slimunit = "Interface\\Addons\\oUF_Smee2\\media\\borders\\slim-unit",
				dek_retro_round_v2 = "Interface\\Addons\\oUF_Smee2\\media\\borders\\dek_retro_round_v2",
				dek_lyt = "Interface\\Addons\\oUF_Smee2\\media\\borders\\dek_lyt.tga",
				
			},
		},
		auras = {
			playerScale = 1.4,
			otherScale = 1,
			timers = {
				enabled = true,
				UsingMMSS = false,
				useEnlargedFonts = true,
				values = {
					DAY = 86400,
					HOUR = 3600,
					MINUTE = 60,
					SHORT = 5
				},
				cooldownTimerStyle = {
					short = {r = 1, g = 0, b = 0, s = .98}, -- <= 5 seconds
					secs = {r = 1, g = 1, b = 0.4, s = 1}, -- < 1 minute
					mins = {r = 0.8, g = 0.8, b = 0.9, s = 1}, -- >= 1 minute
					hrs = {r = 0.8, g = 0.8, b = 0.9, s = 1}, -- >= 1 hr
					days = {r = 0.8, g = 0.8, b = 0.9, s = 1}, -- >= 1 day
				},
			},
			font = {
				size = 8.5,
				name = 'default',
				outline = 'outline',
			}
		},
		frames = {
			locked = true,
			scale = 1,
			font = {
				size = 8.5,
				name = 'default',
				outline = 'outline',
			},
			units = {
				player = {				
					anchorFromPoint = "BOTTOM",
					anchorTo = "UIParent",
					anchorToPoint = "BOTTOM",
					anchorX = 0,
					anchorY = 200,
					width = 230,
					height = 22,
					scale = 1,
					barFading = false,
					range = {
						enabled = false,
						inside = 1,
						outside = .5,
					},
					portraitFrame = {
						enabled = false,
						modelScale = 4.5,
					},
					FontObjects={
						NameText ={
							enabled = true,
							anchorToPoint = "BOTTOM",
							anchorTo = "Health",
							anchorFromPoint = "TOP",
							anchorX = 4,
							anchorY = -4,
							justifyH = "CENTER",
							justifyV = "TOP",
							tag = "[status] [name]",
							desc = "Name",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						HealthText ={
							enabled = true,
							anchorToPoint = "RIGHT",
							anchorTo = "Health",
							anchorFromPoint = "RIGHT",
							anchorX = -4,
							anchorY = 0,
							justifyH = "RIGHT",
							justifyV = "MIDDLE",
							tag = "[curhp]",
							desc = "Health",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						PowerText ={
							enabled = true,
							anchorToPoint = "LEFT",
							anchorTo = "Health",
							anchorFromPoint = "LEFT",
							anchorX = 4,
							anchorY = 0,
							justifyH = "LEFT",
							justifyV = "MIDDLE",
							tag = "[curpp]",
							desc = "Power",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						ThreatText = {
							enabled = true,
							anchorToPoint = "CENTER",
							anchorTo = "Health",
							anchorFromPoint = "CENTER",
							anchorX = 4,
							anchorY = 1,
							justifyH = "CENTER",
							justifyV = "MIDDLE",
							tag = "[threat]",
							desc = "Threat Levels",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						CombatFeedbackText = {
							enabled = true,
							anchorToPoint = "CENTER",
							anchorTo = "Health",
							anchorFromPoint = "CENTER",
							anchorX = 4,
							anchorY = 1,
							justifyH = "CENTER",
							justifyV = "MIDDLE",
							tag = "",
							desc = "Combat Feedback Text",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
					},
					bars = {
						Health = {
							enabled = true,
							dependantOnFrameSize = true,
							classFilter = false,
							reverse = true,
							width = 100,
							height = 80,
							colorDisconnected = true,
							colorClass = false,
							colorTapping = true,
							colorReaction = false,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0.25,0.25,0.25,1},
							BackdropColor = {0,0,0,1},
							Backdrop = "default",
						},
						Power = {
							enabled = true,
							classFilter = false,
							dependantOnFrameSize = true,
							reverse = false,
							width = 100,
							height = 20,
							colorDisconnected = false,
							colorClass = true,
							colorTapping = false,
							colorReaction = false,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0,0,0,0.6},
							BackdropColor = {0,0,0,1},
							Backdrop = "default",
						},
						RuneBar = {
							enabled = true,
							classFilter = "DEATHKNIGHT",
							reverse = false,
							dependantOnFrameSize = false,
							width = 100,
							height = 50,
							anchorFromPoint = "TOP",
							anchorTo = 'parent',
							anchorToPoint = "BOTTOM",
							orientation = "VERTICAL",
							anchorX = 0,
							anchorY = -5,
							padding=2,
							runes = {
								[1] = {
									anchorToPoint="LEFT",
									anchorFromPoint="LEFT",
									anchorTo="runeBar",
									x = 1,
									y = 0,
									width=16.5,
									height=100,
									font = {
										size = 8.5,
										name = 'default',
										outline = '',
									}
								},
								[2] = {
									anchorToPoint="RIGHT",
									anchorFromPoint="LEFT",
									anchorTo=1,
									x = 1,
									y = 0,
									width=16.5,
									height=100,
									font = {
										size = 8.5,
										name = 'default',
										outline = '',
									}
								},
								[3] = {
									anchorToPoint="RIGHT",
									anchorFromPoint="LEFT",
									anchorTo=2,
									x = 1,
									y = 0,
									width=16.5,
									height=100,
									font = {
										size = 8.5,
										name = 'default',
										outline = '',
									}
								},
								[4] = {
									anchorToPoint="RIGHT",
									anchorFromPoint="LEFT",
									anchorTo=3,
									x = 1,
									y = 0,
									width=16.5,
									height=100,
									font = {
										size = 8.5,
										name = 'default',
										outline = '',
									}
								},
								[5] = {
									anchorToPoint="RIGHT",
									anchorFromPoint="LEFT",
									anchorTo=4,
									x = 1,
									y = 0,
									width=16.5,
									height=100,
									font = {
										size = 8.5,
										name = 'default',
										outline = '',
									}
								},
								[6] = {
									anchorToPoint="RIGHT",
									anchorFromPoint="LEFT",
									anchorTo=5,
									width=16.5,
									height=100,
									x = 1,
									y = 0,
									font = {
										size = 8.5,
										name = 'default',
										outline = '',
									}
								},
							},
							bgColor = {1,1,1,.3},
							StatusBarColor = {0.25,0.25,0.25,1},
							BackdropColor = {0,0,0,1},
							Backdrop = "default",
						},
						TotemBar = {
							enabled = true,
							classFilter = "SHAMAN",
							reverse = false,
							dependantOnFrameSize = false,
							anchorFromPoint = "TOP",
							anchorTo = 'parent',
							anchorToPoint = "BOTTOM",
							orientation = "HORIZONTAL",
							anchorX = 0,
							anchorY =10,
							height = 30,
							width = 230,
							scale = 1,
							Timer = {
								justifyH = "CENTER",
								justifyV = "MIDDLE",
								anchorFromPoint = "BOTTOM",
								anchorToPoint = "TOP",
								anchorTo = "totem.icon",
								anchorX = -2,
								anchorY = 0,
								font = {
									size = 8.5,
									name = 'default',
									outline = '',
								}
							},
							bgColor = {1,1,1,.3},
							StatusBarColor = {0.25,0.25,0.25,1},
							BackdropColor = {0,0,0,1},
							Backdrop = "default",
						},
						Castbar = {
							enabled = true,
							announceSpells = true,
							classFilter = false,
							reverse = false,
							anchorFromPoint = "CENTER",
							anchorTo = 'parent',
							anchorToPoint = "CENTER",
							anchorX = 0,
							anchorY = 0,
							height = 28,
							width = 236,
							frameStrata = "BACKGROUND",
							frameLevel = 1,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0,0,0,0.6},
							BackdropColor = {0,0,0,1},
							Backdrop = {
								bgFile = "Interface\\Tooltips\\UI-Tooltip-Background",
								tile = true,
								tileSize = 16,
								insets = {
									left = -1.5,
									right = -1.5,
									top = -1.5,
									bottom = -1.5
								},
							},
							SafeZone={
								enabled = true,
								accurate = true,
								colour = {1, .2, .2, 1},
							},
							Text = {
								justifyH = "LEFT",
								justifyV = "MIDDLE",
								anchorFromPoint = "TOPLEFT",
								anchorToPoint = "BOTTOMLEFT",
								anchorTo = "Castbar",
								anchorX = 2,
								anchorY = 0,
								font = {
									size = 8.5,
									name = 'default',
									outline = '',
								}
							},
							Time = {
								justifyH = "RIGHT",
								justifyV = "MIDDLE",
								anchorFromPoint = "TOPRIGHT",
								anchorToPoint = "BOTTOMRIGHT",
								anchorTo = "Castbar",
								anchorX = -2,
								anchorY = 0,
								font = {
									size = 8.5,
									name = 'default',
									outline = '',
								}
							},
						},
						CoolLine = {
							enabled = true,
							classFilter = false,
							reverse = false,
							dependantOnFrameSize = false,
							anchorFromPoint = "BOTTOM",
							anchorTo = 'parent',
							anchorToPoint = "TOP",
							orientation = "HORIZONTAL",
							anchorX = 0,
							anchorY = 5,
							height = 10,
							width = 230,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0.25,0.25,0.25,1},
							BackdropColor = {0,0,0,1},
							Backdrop = "default",
						}
					},
					DebuffHighlight = {
						Backdrop = true,
						BackDropAlpha = 1,
						Filter = false,
						Icon = false,
					},					
					disallowVehicleSwap = true,
					Buffs = {
						setup = false,
						anchorFromPoint = "RIGHT",
						anchorTo = 'parent',
						anchorToPoint = "LEFT",
						anchorX = -4,
						anchorY = -2,
						["growth-x"] = "LEFT",
						["growth-y"] = "UP",
						Colomns = 16,
						rows = 3,
						count = 22,
						size = 20,
						playerScale = 1.5,
						isSaturated = true,
						isScaled = true,
						spacing = 2,
						filter = nil,
						showOnlyPlayer = nil,
						whitelist = nil,
						blacklist = nil,
					},
					Debuffs = {
						setup = false,
						anchorFromPoint = "LEFT",
						anchorTo = 'parent',
						anchorToPoint = "RIGHT",
						anchorX = 4,
						anchorY = -2,
						["growth-x"] = "RIGHT",
						["growth-y"] = "UP",
						Colomns = 16,
						rows = 3,
						count = 22,
						size = 20,
						playerScale = 1.5,
						isSaturated = true,
						isScaled = true,
						spacing = 1,
						filter = nil,
						showOnlyPlayer = nil,
						whitelist = nil,
						blacklist = nil,
					},
					textures = {
						background = 'default',
						statusbar = 'gloss',
						border = 'slimbuff',
					},
				},
				target = {
					anchorFromPoint = "BOTTOMLEFT",
					anchorTo = "player",
					anchorToPoint = "TOP",
					anchorX = 140,
					anchorY = 45,
					width = 230,
					height = 20,
					scale = 1,
					range = {
						enabled = true,
						inside = 1,
						outside = .5,
					},
					portraitFrame = {
						enabled = false,
						modelScale = 4.5,
					},
					barFading = false,
					FontObjects={
						NameText ={
							enabled = true,
							anchorToPoint = "RIGHT",
							anchorTo = "Power",
							anchorFromPoint = "RIGHT",
							anchorX = -2,
							anchorY = -1,
							justifyH = "RIGHT",
							justifyV = "MIDDLE",
							tag = "[difficulty][shortclassification][level] [factioncolour][abbreviatedname] [dead]",
							desc = "Name",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						HealthText ={
							enabled = true,
							anchorToPoint = "LEFT",
							anchorTo = "Health",
							anchorFromPoint = "LEFT",
							anchorX = 2,
							anchorY = 1,
							justifyH = "LEFT",
							justifyV = "MIDDLE",
							tag = "[perhp]%",
							desc = "Health",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						PowerText ={
							enabled = true,
							anchorToPoint = "RIGHT",
							anchorTo = "Health",
							anchorFromPoint = "RIGHT",
							anchorX = -4,
							anchorY = 1,
							justifyH = "RIGHT",
							justifyV = "MIDDLE",
							tag = "[curpp]",
							desc = "Power",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						ThreatText = {
							enabled = true,
							anchorToPoint = "CENTER",
							anchorTo = "Health",
							anchorFromPoint = "CENTER",
							anchorX = 4,
							anchorY = 1,
							justifyH = "CENTER",
							justifyV = "MIDDLE",
							tag = "[threat]",
							desc = "Threat Level",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						CombatFeedbackText = {
							enabled = true,
							anchorToPoint = "CENTER",
							anchorTo = "Health",
							anchorFromPoint = "CENTER",
							anchorX = 4,
							anchorY = 1,
							justifyH = "CENTER",
							justifyV = "MIDDLE",
							tag = "",
							desc = "Combat Feedback Text",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
					},
					bars = {
						Health = {
							enabled = true,
							classFilter = false,
							dependantOnFrameSize = true,
							reverse = false,
							width = 100,
							height = 80,
							colorDisconnected = true,
							colorClass = false, 
							colorTapping = true,
							colorReaction = false,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0.25,0.25,0.25,1},
							BackdropColor = {0,0,0,1},
							Backdrop = "default",
						},
						Power = {
							enabled = true,
							classFilter = false,
							dependantOnFrameSize = true,
							reverse = false,
							width = 100,
							height = 20,
							colorDisconnected = false,
							colorClass = true,
							colorTapping = false,
							colorReaction = true,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0.25,0.25,0.25,1},
							BackdropColor = {0,0,0,1},
							Backdrop = "default",
						},
						Castbar = {
							enabled = true,
							classFilter = false,
							announceSpells = false,
							anchorFromPoint = "CENTER",
							anchorTo = 'parent',
							anchorToPoint = "CENTER",
							anchorX = 0,
							anchorY = 0,
							height = 28,
							width = 236,
							frameStrata = "BACKGROUND",
							frameLevel = 1,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0,0,0,0.6},
							BackdropColor = {0,0,0,1},
							Backdrop = {
								bgFile = "Interface\\Tooltips\\UI-Tooltip-Background",
								tile = true,
								tileSize = 16,
								insets = {
									left = -1.5,
									right = -1.5,
									top = -1.5,
									bottom = -1.5
								},
							},
							SafeZone={
								enabled = true,
								colour = {1, .2, .2, .5},
							},
							Text = {
								justifyH = "LEFT",
								justifyV = "MIDDLE",
								anchorFromPoint = "LEFT",
								anchorToPoint = "LEFT",
								anchorX = 2,
								anchorY = 0,
								font = {
									size = 8.5,
									name = 'default',
									outline = '',
								}
							},
							Time = {
								justifyH = "RIGHT",
								justifyV = "MIDDLE",
								anchorFromPoint = "RIGHT",
								anchorToPoint = "RIGHT",
								anchorX = -2,
								anchorY = 0,
								font = {
									size = 8.5,
									name = 'default',
									outline = '',
								}
							},
						},
					},
					DebuffHighlight = {
						Backdrop = true,
						Icon = false,
						BackDropAlpha = 1,
						Filter = false,
					},					
					disallowVehicleSwap = true,
					Buffs = {
						setup = false,
						anchorFromPoint = "LEFT",
						anchorTo = 'parent',
						anchorToPoint = "RIGHT",
						anchorX = 4,
						anchorY = -2,
						["growth-x"] = "RIGHT",
						["growth-y"] = "UP",
						Colomns = 16,
						rows = 3,
						count = 22,
						size = 20,
						playerScale = 1.5,
						isSaturated = true,
						isScaled = true,
						spacing = 1,
						filter = nil,
						showOnlyPlayer = nil,
						whitelist = nil,
						blacklist = nil,
					},
					Debuffs = {
						setup = false,
						anchorFromPoint = "LEFT",
						anchorTo = 'parent',
						anchorToPoint = "RIGHT",
						anchorX = 4,
						anchorY = -36,
						["growth-x"] = "RIGHT",
						["growth-y"] = "DOWN",
						Colomns = 16,
						rows = 3,
						count = 22,
						size = 20,
						playerScale = 1.5,
						isSaturated = true,
						isScaled = true,
						spacing = 1,
						filter = nil,
						showOnlyPlayer = nil,
						whitelist = nil,
						blacklist = nil,
					},
					textures = {
						background = 'default',
						statusbar = 'default',
						border = 'default',
					},
				},
				targettarget = {
					anchorFromPoint = "BOTTOMLEFT",
					anchorTo = "target",
					anchorToPoint = "TOPLEFT",
					anchorX = 0,
					anchorY = 15,
					width =165,
					height = 15,
					scale = 1,
					range = {
						enabled = true,
						inside = 1,
						outside = .5,
					},
					portraitFrame = {
						enabled = false,
						modelScale = 4.5,
					},
					barFading = false,
					FontObjects={
						NameText ={
							enabled = true,
							anchorToPoint = "RIGHT",
							anchorTo = "Power",
							anchorFromPoint = "RIGHT",
							anchorX = -2,
							anchorY = -4,
							justifyH = "RIGHT",
							justifyV = "MIDDLE",
							tag = "[difficulty][shortclassification][level] [factioncolour][abbreviatedname] [dead]",
							desc = "Name",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						HealthText ={
							enabled = true,
							anchorToPoint = "LEFT",
							anchorTo = "Health",
							anchorFromPoint = "LEFT",
							anchorX = 2,
							anchorY = 0,
							justifyH = "LEFT",
							justifyV = "MIDDLE",
							tag = "[perhp]%",
							desc = "Health",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						PowerText = {
							enabled = false,
							anchorToPoint = "RIGHT",
							anchorTo = "Health",
							anchorFromPoint = "RIGHT",
							anchorX = -4,
							anchorY = 1,
							justifyH = "RIGHT",
							justifyV = "MIDDLE",
							tag = "[curpp]",
							desc = "Power",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						ThreatText = {
							enabled = true,
							anchorToPoint = "CENTER",
							anchorTo = "Health",
							anchorFromPoint = "CENTER",
							anchorX = 4,
							anchorY = 1,
							justifyH = "CENTER",
							justifyV = "MIDDLE",
							tag = "[threat]",
							desc = "Threat Level",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						CombatFeedbackText = {
							enabled = true,
							anchorToPoint = "CENTER",
							anchorTo = "Health",
							anchorFromPoint = "CENTER",
							anchorX = 4,
							anchorY = 1,
							justifyH = "CENTER",
							justifyV = "MIDDLE",
							tag = "",
							desc = "Combat Feedback Text",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
					},
					bars = {
						Health = {
							enabled = true,
							classFilter = false,
							reverse = false,
							dependantOnFrameSize = true,
							width = 100,
							height = 80,
							colorDisconnected = true,
							colorClass = false, 
							colorTapping = true,
							colorReaction = false,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0.25,0.25,0.25,1},
							BackdropColor = {0,0,0,1},
							Backdrop = "default",
						},
						Power = {
							enabled = true,
							classFilter = false,
							reverse = false,
							dependantOnFrameSize = true,
							width = 100,
							height = 20,
							colorDisconnected = false,
							colorClass = true,
							colorTapping = false,
							colorReaction = true,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0.25,0.25,0.25,1},
							BackdropColor = {0,0,0,1},
							Backdrop = "default",
						},
						Castbar = {
							enabled = true,
							reverse = false,
							announceSpells = false,
							classFilter = false,
							anchorFromPoint = "CENTER",
							anchorTo = 'parent',
							anchorToPoint = "CENTER",
							anchorX = 0,
							anchorY = 0,
							height = 19,
							width = 170,
							frameStrata = "BACKGROUND",
							frameLevel = 1,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0,0,0,0.6},
							BackdropColor = {0,0,0,1},
							Backdrop = {
								bgFile = "Interface\\Tooltips\\UI-Tooltip-Background",
								tile = true,
								tileSize = 16,
								insets = {
									left = -1.5,
									right = -1.5,
									top = -1.5,
									bottom = -1.5
								},
							},
							SafeZone={
								enabled = true,
								colour = {1, .2, .2, .5},
							},
							Text = {
								justifyH = "LEFT",
								justifyV = "MIDDLE",
								anchorFromPoint = "BOTTOMLEFT",
								anchorToPoint = "TOPLEFT",
								anchorX = 2,
								anchorY = 0,
								font = {
									size = 8.5,
									name = 'default',
									outline = '',
								}
							},
							Time = {
								justifyH = "RIGHT",
								justifyV = "MIDDLE",
								anchorFromPoint = "BOTTOMRIGHT",
								anchorToPoint = "TOPRIGHT",
								anchorX = -2,
								anchorY = 0,
								font = {
									size = 8.5,
									name = 'default',
									outline = '',
								}
							},
						},
					},
					DebuffHighlight = {
						Backdrop = true,
						Icon = false,
						BackDropAlpha = 1,
						Filter = false,
					},					
					disallowVehicleSwap = true,
					Buffs = {
						setup = false,
						anchorFromPoint = "RIGHT",
						anchorTo = 'parent',
						anchorToPoint = "LEFT",
						anchorX = 0,
						anchorY = -2,
						["growth-x"] = "LEFT",
						["growth-y"] = "UP",
						Colomns = 16,
						rows = 3,
						count = 22,
						size = 20,
						playerScale = 1.5,
						isSaturated = true,
						isScaled = true,
						spacing = 1,
						filter = nil,
						showOnlyPlayer = nil,
						whitelist = nil,
						blacklist = nil,
					},
					Debuffs = {
						setup = false,
						anchorFromPoint = "LEFT",
						anchorTo = 'parent',
						anchorToPoint = "RIGHT",
						anchorX = 0,
						anchorY = -2,
						["growth-x"] = "RIGHT",
						["growth-y"] = "DOWN",
						Colomns = 16,
						rows = 3,
						count = 22,
						size = 20,
						playerScale = 1.5,
						isSaturated = true,
						isScaled = true,
						spacing = 1,
						filter = nil,
						showOnlyPlayer = nil,
						whitelist = nil,
						blacklist = nil,
					},
					textures = {
						background = 'default',
						statusbar = 'default',
						border = 'default',
					},
				},
				focus = {
					anchorFromPoint = "BOTTOMRIGHT",
					anchorTo = "player",
					anchorToPoint = "TOP",
					anchorX = -140,
					anchorY = 45,
					width = 230,
					height = 20,
					scale = 1,
					barFading = false,
					range = {
						enabled = true,
						inside = 1,
						outside = .5,
					},
					portraitFrame = {
						enabled = false,
						modelScale = 4.5,
					},
					FontObjects={
						NameText ={
							enabled = true,
							anchorToPoint = "LEFT",
							anchorTo = "Power",
							anchorFromPoint = "LEFT",
							anchorX = 4,
							anchorY = -1,
							justifyH = "LEFT",
							justifyV = "MIDDLE",
							tag = "[difficulty][shortclassification][level] [factioncolour][abbreviatedname] [dead]",
							desc = "Name",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						HealthText ={
							enabled = true,
							anchorToPoint = "RIGHT",
							anchorTo = "Health",
							anchorFromPoint = "RIGHT",
							anchorX = -2,
							anchorY = 1,
							justifyH = "RIGHT",
							justifyV = "MIDDLE",
							tag = "[missinghp][perhp]%",
							desc = "Health",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						PowerText ={
							enabled = true,
							anchorToPoint = "LEFT",
							anchorTo = "Health",
							anchorFromPoint = "LEFT",
							anchorX = 4,
							anchorY = 1,
							justifyH = "LEFT",
							justifyV = "MIDDLE",
							tag = "[perpp]%",
							desc = "Power",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						ThreatText = {
							enabled = true,
							anchorToPoint = "CENTER",
							anchorTo = "Health",
							anchorFromPoint = "CENTER",
							anchorX = 4,
							anchorY = 1,
							justifyH = "CENTER",
							justifyV = "MIDDLE",
							tag = "[threat]",
							desc = "Threat Level",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						CombatFeedbackText = {
							enabled = true,
							anchorToPoint = "CENTER",
							anchorTo = "Health",
							anchorFromPoint = "CENTER",
							anchorX = 4,
							anchorY = 1,
							justifyH = "CENTER",
							justifyV = "MIDDLE",
							tag = "",
							desc = "Combat Feedback Text",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
					},
					bars = {
						Health = {
							enabled = true,
							classFilter = false,
							reverse = false,
							dependantOnFrameSize = true,
							width = 100,
							height = 80,
							colorDisconnected = true,
							colorClass = false, 
							colorTapping = true,
							colorReaction = false,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0.25,0.25,0.25,1},
							BackdropColor = {0,0,0,1},
							Backdrop = "default",
						},
						Power = {
							enabled = true,
							classFilter = false,
							reverse = false,
							dependantOnFrameSize = true,
							width = 100,
							height = 20,
							colorDisconnected = false,
							colorClass = true,
							colorTapping = false,
							colorReaction = true,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0.25,0.25,0.25,1},
							BackdropColor = {0,0,0,1},
							Backdrop = "default",
						},
						Castbar = {
							enabled = true,
							classFilter = false,
							reverse = false,
							announceSpells = false,
							anchorFromPoint = "CENTER",
							anchorTo = 'parent',
							anchorToPoint = "CENTER",
							anchorX = 0,
							anchorY = 0,
							height = 31,
							width = 238,
							frameStrata = "BACKGROUND",
							frameLevel = 1,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0,0,0,0.6},
							BackdropColor = {0,0,0,1},
							Backdrop = {
								bgFile = "Interface\\Tooltips\\UI-Tooltip-Background",
								tile = true,
								tileSize = 16,
								insets = {
									left = -1.5,
									right = -1.5,
									top = -1.5,
									bottom = -1.5
								},
							},
							SafeZone={
								enabled = true,
								colour = {1, .2, .2, .5},
							},
							Text = {
								justifyH = "LEFT",
								justifyV = "MIDDLE",
								anchorFromPoint = "LEFT",
								anchorToPoint = "LEFT",
								anchorX = 2,
								anchorY = 0,
								font = {
									size = 8.5,
									name = 'default',
									outline = '',
								}
							},
							Time = {
								justifyH = "RIGHT",
								justifyV = "MIDDLE",
								anchorFromPoint = "RIGHT",
								anchorToPoint = "RIGHT",
								anchorX = -2,
								anchorY = 0,
								font = {
									size = 8.5,
									name = 'default',
									outline = '',
								}
							},
						},
					},
					DebuffHighlight = {
						Backdrop = true,
						Icon = false,
						BackDropAlpha = 1,
						Filter = false,
					},					
					disallowVehicleSwap = true,
					Buffs = {
						setup = false,
						anchorFromPoint = "RIGHT",
						anchorTo = 'parent',
						anchorToPoint = "LEFT",
						anchorX = -4,
						anchorY = -2,
						["growth-x"] = "LEFT",
						["growth-y"] = "UP",
						Colomns = 16,
						rows = 3,
						count = 22,
						size = 20,
						playerScale = 1.5,
						isSaturated = true,
						isScaled = true,
						spacing = 1,
						filter = nil,
						showOnlyPlayer = nil,
						whitelist = nil,
						blacklist = nil,
					},
					Debuffs = {
						setup = false,
						anchorFromPoint = "RIGHT",
						anchorTo = 'parent',
						anchorToPoint = "LEFT",
						anchorX =-4,
						anchorY = -36,
						["growth-x"] = "LEFT",
						["growth-y"] = "DOWN",
						Colomns = 16,
						rows = 3,
						count = 22,
						size = 20,
						playerScale = 1.5,
						isSaturated = true,
						isScaled = true,
						spacing = 1,
						filter = nil,
						showOnlyPlayer = nil,
						whitelist = nil,
						blacklist = nil,
					},
					textures = {
						background = 'default',
						statusbar = 'default',
						border = 'default',
					},
				},
				focustarget = {
					anchorFromPoint = "BOTTOMRIGHT",
					anchorTo = "focus",
					anchorToPoint = "TOPRIGHT",
					anchorX = 0,
					anchorY = 15,
					width = 165,
					height = 15,
					scale = 1,
					range = {
						enabled = true,
						inside = 1,
						outside = .5,
					},
					portraitFrame = {
						enabled = false,
						modelScale = 4.5,
					},
					barFading = false,
					FontObjects={
						NameText ={
							enabled = true,
							anchorToPoint = "LEFT",
							anchorTo = "Power",
							anchorFromPoint = "LEFT",
							anchorX = 4,
							anchorY = -4,
							justifyH = "LEFT",
							justifyV = "MIDDLE",
							tag = "[difficulty][shortclassification][level] [factioncolour][abbreviatedname] [dead]",
							desc = "Name",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						HealthText ={
							enabled = true,
							anchorToPoint = "RIGHT",
							anchorTo = "Health",
							anchorFromPoint = "RIGHT",
							anchorX = -4,
							anchorY = 0,
							justifyH = "RIGHT",
							justifyV = "MIDDLE",
							tag =  "[perhp]%",
							desc = "Health",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						PowerText ={
							enabled = true,
							anchorToPoint = "LEFT",
							anchorTo = "Health",
							anchorFromPoint = "LEFT",
							anchorX = 4,
							anchorY = 1,
							justifyH = "LEFT",
							justifyV = "MIDDLE",
							tag = "[curpp]",
							desc = "Power",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						ThreatText = {
							enabled = true,
							anchorToPoint = "CENTER",
							anchorTo = "Health",
							anchorFromPoint = "CENTER",
							anchorX = 4,
							anchorY = 1,
							justifyH = "CENTER",
							justifyV = "MIDDLE",
							tag = "[threat]",
							desc = "Threat Level",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						CombatFeedbackText = {
							enabled = true,
							anchorToPoint = "CENTER",
							anchorTo = "Health",
							anchorFromPoint = "CENTER",
							anchorX = 4,
							anchorY = 1,
							justifyH = "CENTER",
							justifyV = "MIDDLE",
							tag = "",
							desc = "Combat Feedback Text",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
					},
					bars = {
						Health = {
							enabled = true,
							classFilter = false,
							reverse = false,
							dependantOnFrameSize = true,
							width = 100,
							height = 80,
							colorDisconnected = true,
							colorClass = false, 
							colorTapping = true,
							colorReaction = false,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0.25,0.25,0.25,1},
							BackdropColor = {0,0,0,1},
							Backdrop = "default",
						},
						Power = {
							enabled = true,
							classFilter = false,
							reverse = false,
							dependantOnFrameSize = true,
							width = 100,
							height = 20,
							colorDisconnected = false,
							colorClass = true,
							colorTapping = false,
							colorReaction = true,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0.25,0.25,0.25,1},
							BackdropColor = {0,0,0,1},
							Backdrop = "default",
						},
						Castbar = {
							enabled = true,
							classFilter = false,
							reverse = false,
							announceSpells = false,
							anchorFromPoint = "CENTER",
							anchorTo = 'parent',
							anchorToPoint = "CENTER",
							anchorX = 0,
							anchorY = 0,
							height = 31,
							width = 238,
							frameStrata = "BACKGROUND",
							frameLevel = 1,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0,0,0,0.6},
							BackdropColor = {0,0,0,1},
							Backdrop = {
								bgFile = "Interface\\Tooltips\\UI-Tooltip-Background",
								tile = true,
								tileSize = 16,
								insets = {
									left = -1.5,
									right = -1.5,
									top = -1.5,
									bottom = -1.5
								},
							},
							SafeZone={
								enabled = true,
								colour = {1, .2, .2, .5},
							},
							Text = {
								justifyH = "LEFT",
								justifyV = "MIDDLE",
								anchorFromPoint = "LEFT",
								anchorToPoint = "LEFT",
								anchorX = 2,
								anchorY = 0,
								font = {
									size = 8.5,
									name = 'default',
									outline = '',
								}
							},
							Time = {
								justifyH = "RIGHT",
								justifyV = "MIDDLE",
								anchorFromPoint = "RIGHT",
								anchorToPoint = "RIGHT",
								anchorX = -2,
								anchorY = 0,
								font = {
									size = 8.5,
									name = 'default',
									outline = '',
								}
							},
						},
					},
					DebuffHighlight = {
						Backdrop = true,
						Icon = false,
						BackDropAlpha = 1,
						Filter = false,
					},					
					disallowVehicleSwap = true,
					Buffs = {
						setup = false,
						anchorFromPoint = "RIGHT",
						anchorTo = 'parent',
						anchorToPoint = "LEFT",
						anchorX = 0,
						anchorY = -2,
						["growth-x"] = "LEFT",
						["growth-y"] = "UP",
						Colomns = 16,
						rows = 3,
						count = 22,
						size = 20,
						playerScale = 1.5,
						isSaturated = true,
						isScaled = true,
						spacing = 1,
						filter = nil,
						showOnlyPlayer = nil,
						whitelist = nil,
						blacklist = nil,
					},
					Debuffs = {
						setup = false,
						anchorFromPoint = "LEFT",
						anchorTo = 'parent',
						anchorToPoint = "RIGHT",
						anchorX = 0,
						anchorY = -2,
						["growth-x"] = "RIGHT",
						["growth-y"] = "DOWN",
						Colomns = 16,
						rows = 3,
						count = 22,
						size = 20,
						playerScale = 1.5,
						isSaturated = true,
						isScaled = true,
						spacing = 1,
						filter = nil,
						showOnlyPlayer = nil,
						whitelist = nil,
						blacklist = nil,
					},
					textures = {
						background = 'default',
						statusbar = 'default',
						border = 'default',
					},
				},
				pet = {
					anchorFromPoint = "TOPRIGHT",
					anchorTo = "player",
					anchorToPoint = "BOTTOMLEFT",
					anchorX = 0,
					anchorY = -14,
					width = 145,
					height = 18,
					scale = 1,
					range = {
						enabled = true,
						inside = 1,
						outside = .5,
					},
					portraitFrame = {
						enabled = true,
						modelScale = 4.5,
					},
					FontObjects={
						NameText ={
							enabled = true,
							anchorToPoint = "BOTTOMRIGHT",
							anchorTo = "Health",
							anchorFromPoint = "TOPRIGHT",
							anchorX = 0,
							anchorY = -5,
							justifyH = "RIGHT",
							justifyV = "MIDDLE",
							tag = "[level] [name] [dead]",
							desc = "Name",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						HealthText ={
							enabled = true,
							anchorToPoint = "RIGHT",
							anchorTo = "Health",
							anchorFromPoint = "RIGHT",
							anchorX = -4,
							anchorY = 1,
							justifyH = "RIGHT",
							justifyV = "MIDDLE",
							tag =  "[perhp]%",
							desc = "Health",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						PowerText ={
							enabled = true,
							anchorToPoint = "LEFT",
							anchorTo = "Health",
							anchorFromPoint = "LEFT",
							anchorX = 4,
							anchorY = 1,
							justifyH = "LEFT",
							justifyV = "MIDDLE",
							tag = "[perpp]%",
							desc = "Power",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						ThreatText = {
							enabled = true,
							anchorToPoint = "CENTER",
							anchorTo = "Health",
							anchorFromPoint = "CENTER",
							anchorX = 4,
							anchorY = 1,
							justifyH = "CENTER",
							justifyV = "MIDDLE",
							tag = "[threat]",
							desc = "Threat Level",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						CombatFeedbackText = {
							enabled = true,
							anchorToPoint = "CENTER",
							anchorTo = "Health",
							anchorFromPoint = "CENTER",
							anchorX = 4,
							anchorY = 1,
							justifyH = "CENTER",
							justifyV = "MIDDLE",
							tag = "",
							desc = "Combat Feedback Text",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
					},
					barFading = false,
					bars = {
						Health = {
							enabled = true,
							classFilter = false,
							reverse = false,
							dependantOnFrameSize = true,
							width = 100,
							height = 80,
							colorDisconnected = true,
							colorClass = false, 
							colorTapping = true,
							colorReaction = false,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0.25,0.25,0.25,1},
							BackdropColor = {0,0,0,1},
							Backdrop = "default",
						},
						Power = {
							enabled = true,
							classFilter = false,
							reverse = false,
							dependantOnFrameSize = true,
							width = 100,
							height = 20,
							colorDisconnected = false,
							colorClass = true,
							colorTapping = false,
							colorReaction = true,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0.25,0.25,0.25,1},
							BackdropColor = {0,0,0,1},
							Backdrop = "default",
						},
						Castbar = {
							enabled = true,
							classFilter = false,
							reverse = false,
							announceSpells = false,
							anchorFromPoint = "CENTER",
							anchorTo = 'parent',
							anchorToPoint = "CENTER",
							anchorX = 0,
							anchorY = 0,
							height = 31,
							width = 125,
							frameStrata = "BACKGROUND",
							frameLevel = 1,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0,0,0,0.6},
							BackdropColor = {0,0,0,1},
							Backdrop = {
								bgFile = "Interface\\Tooltips\\UI-Tooltip-Background",
								tile = true,
								tileSize = 16,
								insets = {
									left = -1.5,
									right = -1.5,
									top = -1.5,
									bottom = -1.5
								},
							},
							SafeZone={
								enabled = true,
								colour = {1, .2, .2, .5},
							},
							Text = {
								justifyH = "LEFT",
								justifyV = "MIDDLE",
								anchorFromPoint = "LEFT",
								anchorToPoint = "LEFT",
								anchorX = 2,
								anchorY = 0,
								font = {
									size = 8.5,
									name = 'default',
									outline = '',
								}
							},
							Time = {
								justifyH = "RIGHT",
								justifyV = "MIDDLE",
								anchorFromPoint = "RIGHT",
								anchorToPoint = "RIGHT",
								anchorX = -2,
								anchorY = 0,
								font = {
									size = 8.5,
									name = 'default',
									outline = '',
								}
							},
						},
					},
					DebuffHighlight = {
						Backdrop = true,
						Icon = false,
						BackDropAlpha = 1,
						Filter = false,
					},					
					disallowVehicleSwap = true,
					Buffs = {
						setup = false,
						anchorFromPoint = "RIGHT",
						anchorTo = 'parent',
						anchorToPoint = "LEFT",
						anchorX = -4,
						anchorY = 0,
						["growth-x"] = "LEFT",
						["growth-y"] = "UP",
						Colomns = 16,
						rows = 3,
						count = 22,
						size = 16,
						playerScale = 1.2,
						spacing = 1,
						filter = nil,
						showOnlyPlayer = nil,
						whitelist = nil,
						blacklist = nil,
					},
					Debuffs = {
						setup = false,
						anchorFromPoint = "LEFT",
						anchorTo = 'parent',
						anchorToPoint = "RIGHT",
						anchorX = 0,
						anchorY = -2,
						["growth-x"] = "RIGHT",
						["growth-y"] = "DOWN",
						Colomns = 16,
						rows = 3,
						count = 22,
						size = 20,
						playerScale = 1.5,
						isSaturated = true,
						isScaled = true,
						spacing = 1,
						filter = nil,
						showOnlyPlayer = nil,
						whitelist = nil,
						blacklist = nil,
					},
					textures = {
						background = 'default',
						statusbar = 'default',
						border = 'default',
					},
				},
				pettarget = {
					anchorFromPoint = "TOPLEFT",
					anchorTo = "player",
					anchorToPoint = "BOTTOMRIGHT",
					anchorX = 0,
					anchorY = -14,
					width = 145,
					height = 18,
					scale = 1,
					range = {
						enabled = true,
						inside = 1,
						outside = .5,
					},
					portraitFrame = {
						enabled = false,
						modelScale = 4.5,
					},
					FontObjects={
						NameText ={
							enabled = true,
							anchorToPoint = "BOTTOMLEFT",
							anchorTo = "Health",
							anchorFromPoint = "TOPLEFT",
							anchorX = 0,
							anchorY = -5,
							justifyH = "LEFT",
							justifyV = "MIDDLE",
							tag = "[difficulty][shortclassification][level] [factioncolour][abbreviatedname] [dead]",
							desc = "Name",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						HealthText ={
							enabled = true,
							anchorToPoint = "RIGHT",
							anchorTo = "Health",
							anchorFromPoint = "RIGHT",
							anchorX = -4,
							anchorY = 1,
							justifyH = "RIGHT",
							justifyV = "MIDDLE",
							tag =  "[perhp]%",
							desc = "Health",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						PowerText ={
							enabled = true,
							anchorToPoint = "LEFT",
							anchorTo = "Health",
							anchorFromPoint = "LEFT",
							anchorX = 4,
							anchorY = 1,
							justifyH = "LEFT",
							justifyV = "MIDDLE",
							tag = "[perpp]%",
							desc = "Power",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						ThreatText = {
							enabled = true,
							anchorToPoint = "CENTER",
							anchorTo = "Health",
							anchorFromPoint = "CENTER",
							anchorX = 4,
							anchorY = 1,
							justifyH = "CENTER",
							justifyV = "MIDDLE",
							tag = "[threat]",
							desc = "Threat Level",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
						CombatFeedbackText = {
							enabled = true,
							anchorToPoint = "CENTER",
							anchorTo = "Health",
							anchorFromPoint = "CENTER",
							anchorX = 4,
							anchorY = 1,
							justifyH = "CENTER",
							justifyV = "MIDDLE",
							tag = "",
							desc = "Combat Feedback Text",
							font = {
								size = 8.5,
								name = 'default',
								outline = '',
							}
						},
					},
					barFading = false,
					bars = {
						Health = {
							enabled = true,
							classFilter = false,
							reverse = false,
							dependantOnFrameSize = true,
							width = 100,
							height = 80,
							colorDisconnected = true,
							colorClass = false, 
							colorTapping = true,
							colorReaction = false,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0.25,0.25,0.25,1},
							BackdropColor = {0,0,0,1},
							Backdrop = "default",
						},
						Power = {
							enabled = true,
							classFilter = false,
							reverse = false,
							dependantOnFrameSize = true,
							width = 100,
							height = 20,
							colorDisconnected = false,
							colorClass = true,
							colorTapping = false,
							colorReaction = true,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0.25,0.25,0.25,1},
							BackdropColor = {0,0,0,1},
							Backdrop = "default",
						},
						Castbar = {
							enabled = true,
							classFilter = false,
							reverse = false,
							announceSpells = false,
							anchorFromPoint = "CENTER",
							anchorTo = 'parent',
							anchorToPoint = "CENTER",
							anchorX = 0,
							anchorY = 0,
							height = 31,
							width = 125,
							frameStrata = "BACKGROUND",
							frameLevel = 1,
							bgColor = {1,1,1,.3},
							StatusBarColor = {0,0,0,0.6},
							BackdropColor = {0,0,0,1},
							Backdrop = {
								bgFile = "Interface\\Tooltips\\UI-Tooltip-Background",
								tile = true,
								tileSize = 16,
								insets = {
									left = -1.5,
									right = -1.5,
									top = -1.5,
									bottom = -1.5
								},
							},
							SafeZone={
								enabled = true,
								colour = {1, .2, .2, .5},
							},
							Text = {
								justifyH = "LEFT",
								justifyV = "MIDDLE",
								anchorFromPoint = "LEFT",
								anchorToPoint = "LEFT",
								anchorX = 2,
								anchorY = 0,
								font = {
									size = 8.5,
									name = 'default',
									outline = '',
								}
							},
							Time = {
								justifyH = "RIGHT",
								justifyV = "MIDDLE",
								anchorFromPoint = "RIGHT",
								anchorToPoint = "RIGHT",
								anchorX = -2,
								anchorY = 0,
								font = {
									size = 8.5,
									name = 'default',
									outline = '',
								}
							},
						},
					},
					DebuffHighlight = {
						Backdrop = true,
						Icon = false,
						BackDropAlpha = 1,
						Filter = false,
					},					
					disallowVehicleSwap = true,
					Buffs = {
						setup = false,
						anchorFromPoint = "RIGHT",
						anchorTo = 'parent',
						anchorToPoint = "LEFT",
						anchorX = 0,
						anchorY = -2,
						["growth-x"] = "LEFT",
						["growth-y"] = "UP",
						Colomns = 16,
						rows = 3,
						count = 22,
						size = 20,
						playerScale = 1.5,
						isSaturated = true,
						isScaled = true,
						spacing = 1,
						filter = nil,
						showOnlyPlayer = nil,
						whitelist = nil,
						blacklist = nil,
					},
					Debuffs = {
						setup = false,
						anchorFromPoint = "LEFT",
						anchorTo = 'parent',
						anchorToPoint = "RIGHT",
						anchorX = 0,
						anchorY = -2,
						["growth-x"] = "RIGHT",
						["growth-y"] = "DOWN",
						Colomns = 16,
						rows = 3,
						count = 22,
						size = 20,
						playerScale = 1.5,
						isSaturated = true,
						isScaled = true,
						spacing = 1,
						filter = nil,
						showOnlyPlayer = nil,
						whitelist = nil,
						blacklist = nil,
					},
					textures = {
						background = 'default',
						statusbar = 'default',
						border = 'default',
					},
				}
			}
		}
	}
}

setmetatable(oUF_Smee_Settings.profile.colors.class, {
	__index = function(self, key)
		return { 0.78, 0.61, 0.43 }
	end
})
